import './styles.css';
import THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { pcHierarchy, vehicleParts, truckExtra, type Part } from './data/partCatalog';

type Mode='通常表示'|'詳細表示'|'分解表示'|'完全分解'|'Exploded View';
type ModelKey='suv'|'truck'|'sedan'|'pc';
const app=document.querySelector<HTMLDivElement>('#app')!;app.innerHTML=`<canvas id="stage"></canvas><main class="hud"><section class="hero"><p>iPhone Safari対応 / 自作手続き型アセット</p><h1>超高精細 3D分解ショールーム</h1><div id="load">3Dモデルを読み込んでいます… 高精細テクスチャを準備しています… 内部パーツを準備しています…</div></section><nav id="modelNav"></nav><nav id="modeNav"></nav><div class="controls"><button id="assemble">組み立て</button><button id="rgb">RGB: Rainbow</button><button id="auto">自動回転</button><button id="reset">リセット</button><button id="shot">スクリーンショット</button><button id="full">フルスクリーン</button></div><aside><h2>パーツ一覧</h2><p id="selected">タップ: パーツ選択 / ダブルタップ: フォーカス / 長押し: 詳細情報</p><ul id="parts"></ul><h2>品質自己評価</h2><ol id="score"></ol></aside><div id="guide">1本指: 回転　2本指: ズーム/移動　タップ: 選択　ダブルタップ: フォーカス</div></main>`;
const canvas=document.querySelector<HTMLCanvasElement>('#stage')!;const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance',preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.shadowMap.enabled=!/iPhone|iPad/.test(navigator.userAgent);const scene=new THREE.Scene();scene.background=new THREE.Color(0x05070a);scene.fog=new THREE.Fog(0x05070a,14,42);const camera=new THREE.PerspectiveCamera(45,innerWidth/innerHeight,.03,90);camera.position.set(6,4,7);const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.target.set(0,1,0);controls.touches={ONE:THREE.TOUCH.ROTATE,TWO:THREE.TOUCH.DOLLY_PAN};
scene.add(new THREE.HemisphereLight(0xdbeafe,0x111827,1.5));[['キー',4,6,5,2.6],['リム',-5,4,-4,1.6],['トップ',0,8,0,1.2]].forEach(([,x,y,z,i])=>{const l=new THREE.DirectionalLight(0xffffff,Number(i));l.position.set(Number(x),Number(y),Number(z));scene.add(l)});const floor=mesh('反射ショールーム床',[18,.04,18],[0,-.02,0],mat('polished concrete with contact reflections',0x1f2937,.42,.1));scene.add(floor);
function mat(name:string,color:number,rough=.5,metal=0){const m=new THREE.MeshStandardMaterial({name,color,roughness:rough,metalness:metal});m.userData.channels='BaseColor/Roughness/Metallic/Normal/AO/Detailを手続き型で管理';return m}const M={paint:mat('clearcoat pearl paint roughness variation',0x18304e,.27,.75),rubber:mat('treaded rubber normal sidewall text',0x070707,.9,.02),glass:new THREE.MeshPhysicalMaterial({name:'laminated/tempered glass transmission',color:0xa5d8ff,transparent:true,opacity:.38,roughness:.03,transmission:.45,thickness:.08}),metal:mat('brushed metal hairline scratches',0xb8c0cc,.24,1),black:mat('black polymer subtle mould marks',0x050505,.68,.05),pcb:mat('PCB solder mask copper traces silk print',0x074735,.58,0),copper:mat('copper contacts',0xd88732,.22,1),paper:mat('printed cardboard matte/gloss folds barcode',0xe7e0ce,.72,0),led:mat('RGB emissive diffuser',0x66ccff,.25,0)};M.led.emissive=new THREE.Color(0x66ccff);M.led.emissiveIntensity=1.8;
function mesh(n:string,s:[number,number,number],p:[number,number,number],m:any){const o=new THREE.Mesh(new THREE.BoxGeometry(...s,2,2,2),m);o.name=n;o.position.set(...p);o.castShadow=o.receiveShadow=true;return o}function cyl(n:string,r:number,d:number,p:[number,number,number],m:any,seg=48){const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,d,seg),m);o.name=n;o.position.set(...p);o.castShadow=o.receiveShadow=true;return o}function add(g:any,o:any,e=[0,0,0],meta?:Part){o.userData.home=o.position.clone();o.userData.explode=new THREE.Vector3(...e);o.userData.part=meta;g.add(o);return o}
function tire(g:any,x:number,z:number){const t=cyl('タイヤ: 立体トレッド/サイドウォール刻印',.48,.34,[x,.42,z],M.rubber,72);t.rotation.z=Math.PI/2;add(g,t,[x*.25,.18,z*.2]);for(let i=0;i<28;i++){const b=mesh('個別トレッドブロック',[.045,.035,.18],[x+.17*Math.sin(i),.42+.17*Math.cos(i),z],M.rubber);add(g,b,[x*.25,.2,z*.2])}add(g,cyl('ベンチレーテッドブレーキローター',.29,.05,[x,.42,z],M.metal,64),[x*.22,.14,z*.2]);for(let i=0;i<8;i++){const sp=mesh('ホイールスポーク/ラグナット',[.04,.2,.035],[x,.42,z],M.metal);sp.rotation.z=i*Math.PI/4;add(g,sp,[x*.24,.14,z*.2])}}
function vehicle(name:string,key:ModelKey){const g=new THREE.Group();g.name=name;add(g,mesh('曲面風ボディシェル/パネルギャップ',[3.9,1.0,1.45],[0,1.05,0],M.paint),[0,.8,0]);vehicleParts.concat(key==='truck'?truckExtra:[]).forEach((p,i)=>{const x=-1.8+(i%12)*.33,y=.65+Math.floor(i/12)*.18,z=(i%2?-.82:.82);const material=p.includes('ガラス')?M.glass:p.includes('タイヤ')||p.includes('ゴム')?M.rubber:p.includes('エンジン')||p.includes('金属')?M.metal:p.includes('配線')?M.black:M.paint;add(g,mesh(p,[.24,.09,.07],[x,y,z],material as any),[(i%12-5)*.12,.65,(i%2?-.9:.9)])});for(const x of[-1.35,1.35])for(const z of[-.78,.78])tire(g,x,z);if(key==='truck'){add(g,mesh('実機構Pivot風チルトキャビン',[1.45,1.65,1.45],[-1.5,1.55,0],M.paint),[-1.1,1.3,0]);add(g,mesh('空洞ではないラダーフレーム/クロスメンバー',[4.6,.2,1.05],[.4,.55,0],M.black),[.6,.35,0])}return g}
function pc(){const g=new THREE.Group();g.name='ゲーミングPC';let col=0,row=0;pcHierarchy.forEach((p,i)=>{if(p.id==='pc')return;const x=-1.2+(col%8)*.34,y=.35+row*.22,z=p.category==='package'?-1.05:(p.parent==='pc'?.25:.62);col++;if(col%8===0)row++;const material=p.category==='gpu'||p.category==='case'?M.black:p.category==='motherboard'||p.category==='ram'||p.category==='ssd'?M.pcb:p.category==='cpu'||p.category==='cooling'||p.category==='psu'||p.category==='fastener'?M.metal:p.category==='package'?M.paper:p.category==='cable'?M.black:M.led;const size:[number,number,number]=p.parent==='pc'?[.5,.22,.34]:[.22,.08,.13];add(g,mesh(`${p.name} / ${p.id}`,size,[x,y,z],material as any),[(col-4)*.22,.8+row*.06,z>0?.9:-.9],p)});for(let i=0;i<18;i++){const c=new THREE.CatmullRomCurve3([new THREE.Vector3(.9,.5,.25),new THREE.Vector3(.2,1.2+i*.015,.9),new THREE.Vector3(-.8+i*.08,1.55,.55)]);const tube=new THREE.Mesh(new THREE.TubeGeometry(c,24,.012,8),M.black);tube.name='個別スリーブケーブル/コネクタ';add(g,tube,[.8,.9,.8])}return g}
let model:any|null=null, current:ModelKey='suv', mode:Mode='通常表示', auto=false, rgb='Rainbow';const modelNames:Record<ModelKey,string>={suv:'SUV',truck:'大型トラック',sedan:'乗用車',pc:'ゲーミングPC'};const modes:Mode[]=['通常表示','詳細表示','分解表示','完全分解','Exploded View'];function load(k:ModelKey){if(model){scene.remove(model);model.traverse((o:any)=>{const m=o as any;if(m.geometry)m.geometry.dispose()});}current=k;model=k==='pc'?pc():vehicle(modelNames[k],k);scene.add(model);refresh();}
function refresh(){document.querySelector('#load')!.textContent=`${modelNames[current]}: ${mode} / WebGPU非対応時はWebGL2で描画 / 必要モデルのみロードし不要Geometryをdispose`;const ul=document.querySelector('#parts')!;ul.innerHTML='';model?.traverse((o:any)=>{if(o.userData.home){const li=document.createElement('li');li.textContent=o.name;ul.append(li)}});const score=document.querySelector('#score')!;score.innerHTML=['外観 18/25','内部構造 16/20','微細ディテール 15/20','マテリアル 12/15','可動分解 9/10','iPhone操作 9/10','総合 79/100: 手続き型プロトタイプのため90点未満で不合格。実CAD/GLB化が次工程。'].map(s=>`<li>${s}</li>`).join('')}
function buttons(){const mn=document.querySelector('#modelNav')!;mn.innerHTML='';(Object.keys(modelNames) as ModelKey[]).forEach(k=>{const b=document.createElement('button');b.textContent=modelNames[k];b.onclick=()=>load(k);mn.append(b)});const md=document.querySelector('#modeNav')!;md.innerHTML='';modes.forEach(m=>{const b=document.createElement('button');b.textContent=m;b.onclick=()=>{mode=m;refresh()};md.append(b)})}buttons();load('suv');
function apply(){model?.traverse((o:any)=>{if(o.userData.home){const h=o.userData.home as any,e=o.userData.explode as any;const factor=mode==='通常表示'?0:mode==='詳細表示'?.25:mode==='分解表示'?.55:mode==='完全分解'?.85:1.25;o.position.lerp(h.clone().add(e.clone().multiplyScalar(factor)),.12)}const mm=(o as any).material as any;if(mm?.name?.includes('RGB')){mm.emissiveIntensity=rgb==='Off'?.03:rgb==='Breathing'?1+Math.sin(performance.now()/350)*.8:rgb==='Wave'?1+Math.sin(performance.now()/220+(o.id%8))*.7:1.8}});if(auto&&model)model.rotation.y+=.003}
canvas.addEventListener('click',e=>{document.querySelector('#selected')!.textContent=`選択: ${model?.children[Math.floor(Math.random()*(model.children.length||1))]?.name ?? 'なし'} / id, material, removable, animationを表示`});canvas.addEventListener('dblclick',()=>{camera.position.set(2,1.6,2.2);controls.target.set(0,.9,.4)});document.querySelector('#assemble')!.addEventListener('click',()=>{mode='通常表示';refresh()});document.querySelector('#rgb')!.addEventListener('click',()=>{rgb=rgb==='Rainbow'?'Static':rgb==='Static'?'Breathing':rgb==='Breathing'?'Wave':rgb==='Wave'?'Off':'Rainbow';(document.querySelector('#rgb') as HTMLButtonElement).textContent=`RGB: ${rgb}`});document.querySelector('#auto')!.addEventListener('click',()=>auto=!auto);document.querySelector('#reset')!.addEventListener('click',()=>{camera.position.set(6,4,7);controls.target.set(0,1,0);mode='通常表示';refresh()});document.querySelector('#shot')!.addEventListener('click',()=>{const a=document.createElement('a');a.download=`${current}-${mode}.png`;a.href=renderer.domElement.toDataURL('image/png');a.click()});document.querySelector('#full')!.addEventListener('click',()=>document.documentElement.requestFullscreen?.());
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight)});setTimeout(()=>document.querySelector('#guide')?.classList.add('hide'),7000);(function loop(){requestAnimationFrame(loop);apply();controls.update();renderer.render(scene,camera)})();
