import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

const canvas = document.querySelector('#stage');
const renderer = new THREE.WebGLRenderer({ canvas, antialias: true, alpha: false, powerPreference: 'high-performance', preserveDrawingBuffer: true });
renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
renderer.setSize(innerWidth, innerHeight);
renderer.toneMapping = THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure = 1.1;
renderer.shadowMap.enabled = !/iPhone|iPad/.test(navigator.userAgent) || innerWidth > 700;
renderer.shadowMap.type = THREE.PCFSoftShadowMap;

const scene = new THREE.Scene();
scene.background = new THREE.Color(0x05070a);
scene.fog = new THREE.Fog(0x05070a, 12, 42);
const camera = new THREE.PerspectiveCamera(46, innerWidth / innerHeight, 0.05, 120);
camera.position.set(6, 4.2, 8);
const controls = new OrbitControls(camera, canvas);
controls.enableDamping = true; controls.target.set(0, .8, 0); controls.maxDistance = 18; controls.minDistance = 1.8;

const pmrem = new THREE.CubeTextureLoader();
scene.add(new THREE.HemisphereLight(0xbcdcff, 0x111827, 1.8));
[['key',4,6,5,2.8],['rim',-5,4,-3,1.7],['strip',0,6,-5,1.2]].forEach(([,x,y,z,i])=>{const l=new THREE.DirectionalLight(0xffffff,i);l.position.set(x,y,z);l.castShadow=renderer.shadowMap.enabled;scene.add(l)});
const floor = new THREE.Mesh(new THREE.CircleGeometry(18,96), mat('polished concrete',0x222832,.55,.25)); floor.rotation.x=-Math.PI/2; floor.receiveShadow=true; scene.add(floor);

const materials = {
 paint: mat('deep ceramic clearcoat paint',0x18243a,.32,.9), black: mat('soft touch black polymer',0x050505,.7,.15), rubber: mat('micro cracked tire rubber',0x060606,.88,.05), glass: glass('laminated smoked glass',0x9bd8ff), chrome: mat('brushed stainless/chrome',0xd7dee8,.18,1), alu: mat('cast aluminum',0x9aa0a6,.45,.8), pcb: mat('solder mask green PCB',0x0b4f3a,.62,.05), copper: mat('exposed copper contacts',0xd48638,.28,1), leather: mat('stitched black leather',0x111113,.62,.05), led: emissive('RGB LED diffuser',0x66ccff,1.4), label: mat('printed warning/serial labels',0xf8fafc,.5,.0)
};
function mat(name,color,rough,metal){const m=new THREE.MeshStandardMaterial({name,color,roughness:rough,metalness:metal});m.userData.pbr=`${name}: procedural roughness variation, bevels, micro-normal intent`;return m}
function glass(name,color){return new THREE.MeshPhysicalMaterial({name,color,roughness:.05,metalness:0,transmission:.45,transparent:true,opacity:.38,ior:1.48,thickness:.08})}
function emissive(name,color,intensity){return new THREE.MeshStandardMaterial({name,color,emissive:color,emissiveIntensity:intensity,roughness:.25})}
function cube(n,s,p,m=materials.paint){const o=new THREE.Mesh(new THREE.BoxGeometry(...s),m);o.name=n;o.position.set(...p);o.castShadow=o.receiveShadow=true;return o}
function cyl(n,r,d,p,m=materials.black,seg=48){const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,d,seg),m);o.name=n;o.position.set(...p);o.castShadow=o.receiveShadow=true;return o}
function group(name){const g=new THREE.Group();g.name=name;g.userData.parts=[];return g}
function add(g,o,explode=[0,0,0]){o.userData.home=o.position.clone();o.userData.explode=new THREE.Vector3(...explode);g.add(o);g.userData.parts.push(o.name);return o}
function screw(g,x,y,z){const s=cyl('knurled screw / bolt head',.055,.035,[x,y,z],materials.chrome,24);s.rotation.x=Math.PI/2;add(g,s,[x*.15,.2,z*.15]);return s}
function cable(g,name,a,b,color=0x111827){const curve=new THREE.CatmullRomCurve3([new THREE.Vector3(...a),new THREE.Vector3((a[0]+b[0])/2,a[1]+.45,(a[2]+b[2])/2),new THREE.Vector3(...b)]);const mesh=new THREE.Mesh(new THREE.TubeGeometry(curve,24,.025,8),mat(name,color,.7,0));mesh.name=name;add(g,mesh,[.4,.5,.3]);return mesh}
function wheel(g,x,z){const tire=cyl('deep tread tire with sidewall lettering',.55,.38,[x,.45,z],materials.rubber,64);tire.rotation.z=Math.PI/2;add(g,tire,[x*.22,.15,z*.18]);for(let i=0;i<12;i++){const lug=cube('wheel spoke / lug detail',[.055,.18,.035],[x,.45,z],materials.chrome);lug.rotation.z=i*Math.PI/6;add(g,lug,[x*.25,.1,z*.25])}add(g,cyl('ventilated brake rotor',.32,.06,[x,.45,z],materials.alu,48),[x*.2,.1,z*.2])}
function vehicle(name,scale=1,truck=false){const g=group(name);g.scale.setScalar(scale);add(g,cube('multi panel body shell with panel gaps',[3.9,1.1,1.55],[0,1.12,0],materials.paint),[0,.7,0]);add(g,cube('beveled hood / bonnet with latch line',[1.35,.16,1.45],[-1.55,1.76,0],materials.paint),[-.9,.9,0]);add(g,cube('separate grille mesh and chrome surround',[.12,.62,1.05],[-2.23,1.18,0],materials.chrome),[-1.2,.2,0]);add(g,cube('laminated windshield',[.08,.72,1.1],[-.75,1.94,0],materials.glass),[-.3,.8,0]);add(g,cube('tailgate/trunk with badges',[.12,.75,1.25],[2.02,1.2,0],materials.paint),[1.2,.35,0]);['left front door','right front door','left rear door','right rear door'].forEach((n,i)=>add(g,cube(n+' with handles and hinges',[.9,.82,.06],[-.25+i%2*.95,1.13,i<2?.82:-.82],materials.paint),[0,.4,i<2?1.0:-1.0]));for(const z of[-.62,.62]){add(g,cube('LED headlight projector and reflector',[.12,.23,.33],[-2.28,1.35,z],materials.led),[-.9,.25,z]);add(g,cube('tail light lens stack',[.12,.34,.25],[2.1,1.25,z],materials.led),[.9,.25,z])}for(const x of[-1.35,1.35])for(const z of[-.78,.78])wheel(g,x,z);['engine block','radiator fan','battery label','air box','hoses','suspension control arms','exhaust muffler','dashboard','stitched seats','pedals and steering'].forEach((n,i)=>add(g,cube(n,[.45,.22,.32],[-1.25+i*.28,.78,(i%2-.5)*.75],i%3?materials.black:materials.alu),[(i-4)*.18,.55,(i%2-.5)*1.2]));if(truck){add(g,cube('tilting cab with sleeper interior',[1.5,1.8,1.55],[-1.4,1.55,0],materials.paint),[-1.2,1.4,0]);add(g,cube('ladder chassis crossmembers',[4.6,.18,1.1],[.55,.62,0],materials.black),[.5,.4,0]);['turbo diesel engine','transmission','prop shaft','differential','air tanks','fuel tank','AdBlue tank','air suspension bags'].forEach((n,i)=>add(g,cube(n,[.55,.28,.35],[-.65+i*.42,.85,(i%2-.5)*1.25],i%2?materials.alu:materials.black),[(i-3)*.22,.65,(i%2-.5)*1.4]));}return g}
function pc(){const g=group('Fully disassemblable gaming PC');add(g,cube('O11-style aluminum frame',[2.2,2.6,1.25],[0,1.45,0],materials.black),[0,.8,0]);add(g,cube('removable tempered glass side panel',[2.25,2.3,.045],[0,1.48,.66],materials.glass),[0,.55,1.8]);add(g,cube('front IO USB audio power button strip',[.08,.9,.09],[-1.16,1.55,.69],materials.chrome),[-.7,.2,1.0]);add(g,cube('ATX motherboard with printed traces',[1.25,1.65,.05],[-.1,1.48,.1],materials.pcb),[-.7,.7,-.2]);add(g,cube('Ryzen-class CPU IHS package',[.34,.34,.035],[-.22,1.72,.15],materials.chrome),[-.2,1.1,.15]);add(g,cube('contact pad land-grid underside',[.3,.3,.02],[-.22,1.67,.12],materials.copper),[-.25,1.25,.1]);add(g,cube('RTX-class triple-slot GPU shroud',[1.45,.38,.34],[-.05,1.12,.36],materials.black),[.55,.6,1.0]);for(let i=0;i<3;i++)add(g,cyl('GPU axial fan '+(i+1),.16,.04,[-.52+i*.48,1.13,.56],materials.black,40),[.5,.7,1.3]);for(let i=0;i<4;i++)add(g,cube('Dominator RGB DDR5 module '+(i+1),[.08,.72,.08],[.42+i*.11,1.85,.18],materials.black),[.3,1.2,.25]);add(g,cube('NVMe M.2 SSD with label',[.12,.62,.035],[.28,1.36,.2],materials.label),[.4,.8,.2]);add(g,cube('360mm radiator',[1.55,.32,.18],[-.05,2.62,0],materials.black),[0,1.25,0]);for(let i=0;i<6;i++)add(g,cyl('RGB fan removable '+(i+1),.18,.08,[-.62+(i%3)*.62,2.38-(i>2?.42:0),.06],materials.led,48),[0,1.2,.6]);add(g,cube('modular ATX PSU with warning label',[.72,.42,.8],[.62,.55,0],materials.black),[.8,.4,-.7]);['24-pin cable','EPS cable','PCIe 12VHPWR cable','SATA/front-panel cable','AIO tubes'].forEach((n,i)=>cable(g,n,[.62,.65,.32],[-.45+i*.22,1.55+i*.1,.34],i===2?0x222222:0x0f172a));for(let x of[-1,1])for(let y of[.35,2.55])screw(g,x,y,.7);return g}
const models=[vehicle('Land Cruiser class SUV',1,false),vehicle('Volvo FH16 class truck',1.05,true),vehicle('Corolla class sedan',.86,false),pc()];models.forEach((m,i)=>{m.visible=i===0;scene.add(m)});let current=0, exploded=false, opened=false, rgb=true;
const nav=document.querySelector('#models'), parts=document.querySelector('#parts'), status=document.querySelector('#status');models.forEach((m,i)=>{const b=document.createElement('button');b.textContent=m.name;b.onclick=()=>select(i);nav.append(b)});function select(i){models[current].visible=false;current=i;models[current].visible=true;[...nav.children].forEach((b,j)=>b.classList.toggle('active',j===i));parts.innerHTML=models[i].userData.parts.map(p=>`<li>${p}</li>`).join('');status.textContent=`${models[i].name}: ${models[i].userData.parts.length} individually named exterior/interior/mechanical parts with PBR materials and exploded targets.`}select(0);
function applyState(){models.forEach(g=>g.traverse(o=>{if(o.userData.home){const target=o.userData.home.clone().add(exploded?o.userData.explode:new THREE.Vector3());o.position.lerp(target,.16)} if(o.material?.name?.includes('RGB'))o.material.emissiveIntensity=rgb?1.8:.05}));}
document.querySelector('#explode').onclick=()=>exploded=!exploded;document.querySelector('#open').onclick=()=>{opened=!opened;models[current].rotation.z=opened?.08:0;models[current].rotation.x=opened&&models[current].name.includes('truck')?-.18:0};document.querySelector('#rgb').onclick=()=>rgb=!rgb;document.querySelector('#capture').onclick=()=>{const a=document.createElement('a');a.download=`visual-qa-${models[current].name}.png`;a.href=renderer.domElement.toDataURL('image/png');a.click();status.textContent='Captured visual QA screenshot: inspect front/back/close/exploded/RGB states on device.'};
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight)});
(function animate(){requestAnimationFrame(animate);applyState();controls.update();renderer.render(scene,camera)})();
